-- MySQL Script generated by MySQL Workbench
-- Wed Jan 27 10:01:58 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `message`.`user` ;

CREATE TABLE IF NOT EXISTS `message`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `nom_user` VARCHAR(45) NULL,
  `prenom_user` VARCHAR(45) NULL,
  `password_user` VARCHAR(45) NULL,
  `mail_user` VARCHAR(45) NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`gestion_message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `message`.`gestion_message` ;

CREATE TABLE IF NOT EXISTS `essage`.`gestion_message` (
  `id_message` INT NOT NULL AUTO_INCREMENT,
  `contenu_message` VARCHAR(255) NULL,
  `user_id_user` INT NOT NULL,
  PRIMARY KEY (`id_message`),
  INDEX `fk_gestion_message_user_idx` (`user_id_user` ASC) VISIBLE,
  CONSTRAINT `fk_gestion_message_user`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `message`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
